name: Run Riona Agent

on:
  push:
    branches: [ main ]
  workflow_dispatch:  
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout this repo
      uses: actions/checkout@v4

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0

    - run: npm install

    - name: Create env file
      run: |
        echo IGusername=${{ secrets.IG_USERNAME}} >> .env
        echo IGpassword=${{ secrets.IG_PASSWORD }} >> .env
        cat .env
    
    - run: npm start