name: Run Riona Agent

on:
  push:
    branches: [ main ]
  workflow_dispatch:  
    
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
    - run: ls -la
    - run: cd Riona-AI-Agent
    - name: Install dependencies with npm
      run: npm install
    - name: Create env file
      run: |
        touch .env
        echo IGusername=${{ secrets.IG_USERNAME}} >> .env
        echo IGpassword=${{ secrets.IG_PASSWORD }} >> .env
        cat .env
    - run: npm start